apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    online: dyh-data-portal-master
  name: dyh-data-portal-master
  namespace: dyh-master
spec:
  replicas: 2
  selector:
    matchLabels:
      online: dyh-data-portal-master
  template:
    metadata:
      labels:
        online: dyh-data-portal-master
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: ${IMAGE}
        name: app
        resources:
          limits:
            # cpu: "500m"      #指定nginx容器的vCPU为0.5 vCPU
            memory: "2Gi"   #指定nginx容器的内存为1 GiB
        env:
          - name: aliyun_logs_dyh-data-portal-master
            value: /logs/*.log
          - name: JAVA_OPTS
            value: '-Duser.timezone=Asia/Shanghai -Dfile.encoding=UTF-8 -Dnacos.host=mse-246325f0-nacos-ans.mse.aliyuncs.com:8848 -Dspring.profiles.active=prod -Dnacos.namespace=prod'
        readinessProbe:
          httpGet:
            port: 8080
            path: /healthy/check
            scheme: HTTP
          initialDelaySeconds: 75
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            port: 8080
            path: /healthy/check
            scheme: HTTP
          initialDelaySeconds: 90
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: dyh-data-portal-service
  namespace: dyh-master
  labels:
    online: master
    labele2: label
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    online: dyh-data-portal-master
  sessionAffinity: None
  type: ClusterIP
  
  

              
              
